### ISSUE TITLE
choping fingerprint bug

### ISSUE THREAD

**Issue by railenikeev** [GoogleChinaCEO/device_xiaomi_chopin#4]
Fingerprint working like a touchscreen on choping. On video i'm don't touching screen(except for home gesture).
This bug on all roms.

https://user-images.githubusercontent.com/52450957/167912263-fb5ec840-aa3d-4ece-b49e-679b2a264ae1.mp4

[2022-04-30-18-05-06.txt](https://github.com/Yuyuko1024/device_xiaomi_chopin/files/8672168/2022-04-30-18-05-06.txt)

**Comment by railenikeev** [comment]
https://user-images.githubusercontent.com/52450957/167913156-cce68960-8eeb-4e52-a52d-b0ce962bfb67.mp4


[2022-04-30-17-52-03.txt](https://github.com/Yuyuko1024/device_xiaomi_chopin/files/8672247/2022-04-30-17-52-03.txt)

**Comment by Yuyuko1024** [comment]
Because the fingerprint module defines the tap operation as a special physical key input in the original ROM, it is misidentified as keyboard input in the AOSP. You can temporarily delete or comment out the key definitions in the uinput-Goodix.kl file in config/keylayout and uinput-fpc.kl and override them as Magisk modules
